services:
  # Main Discord Bot Service
  blockate-audio-bot:
    build: ./bot
    image: blockate/audio-bot:latest
    container_name: blockate-audio-bot
    restart: unless-stopped
    environment:
      # Discord Configuration
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OWNERS=${OWNERS}
      
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      
      # Notification Service
      - NTFY_AUTH=${NTFY_AUTH}
      - NTFY_USER=${NTFY_USER}
      - NTFY_PASSWORD=${NTFY_PASSWORD}
      
      # Audio Service
      - AUDIO_FILE_PROXY_AUTH=${AUDIO_FILE_PROXY_AUTH}
      - ROBLOX_ACCOUNT_COOKIE=${ROBLOX_ACCOUNT_COOKIE}
      
      # Node Environment
      - NODE_ENV=production
    
    volumes:
      # Bot data directory
      - ./bot/data:/app/data:rw
      # Shared IPC directory for communication with selfbot
      - ./shared/ipc:/app/ipc:rw
    
    networks:
      - blockate-network
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    depends_on:
      - ntfy

  # Discord Selfbot Service
  blockate-audio-selfbot:
    build: ./selfbot
    image: blockate/audio-selfbot:latest
    container_name: blockate-audio-selfbot
    restart: unless-stopped
    environment:
      # Discord Selfbot Configuration
      - ACCOUNT_TOKEN=${ACCOUNT_TOKEN}
      - ROBLOX_ACCOUNT_TOKEN=${ROBLOX_ACCOUNT_TOKEN}

      # Node Environment
      - NODE_ENV=production

    volumes:
      # Shared IPC directory for communication with main bot
      - ./shared/ipc:/app/ipc:rw

    networks:
      - blockate-network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    depends_on:
      - blockate-audio-bot

  # Notification Service (ntfy)
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: blockate-ntfy
    restart: unless-stopped
    ports:
      - "3462:80"
    volumes:
      - ./bot/ntfy:/var/lib/ntfy
    environment:
      - NTFY_AUTH_USERNAME=${NTFY_USER}
      - NTFY_AUTH_PASSWORD=${NTFY_PASSWORD}
    command: serve
    
    networks:
      - blockate-network
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: PostgreSQL database if needed locally
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: blockate-postgres
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_DB=${POSTGRES_DB:-blockate}
  #     - POSTGRES_USER=${POSTGRES_USER:-postgres}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - blockate-network

networks:
  blockate-network:
    driver: bridge

# Uncomment the volumes section below if using local PostgreSQL
# volumes:
#   postgres_data: